# Gunakan image PHP + Apache
FROM php:8.2-apache

# Install ekstensi dan utilitas yang dibutuhkan Laravel
RUN apt-get update && apt-get install -y \
    libzip-dev unzip zip curl git libpng-dev libonig-dev \
    && docker-php-ext-install pdo pdo_mysql zip gd

# Install Composer dari official image
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# Copy semua file proyek ke container
COPY . /var/www/html

# Set working directory
WORKDIR /var/www/html

# Set permission & aktifkan mod_rewrite
RUN chown -R www-data:www-data /var/www/html \
    && a2enmod rewrite

# Jalankan proses build Laravel
RUN composer install --no-dev --optimize-autoloader \
    && php artisan config:cache \
    && php artisan route:cache \
    && php artisan view:cache \
    && php artisan storage:link

# Laravel akan dijalankan di port default Apache (80)
EXPOSE 80
